# Jekyll configuration

name: massage-by-donna-read
description: The website of Queensland masseuse Donna Read
author:
  name: Mike Causer
  email: mcauser@gmail.com

url: http://donna-read.github.io/massage-by-donna-read

exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]

sass:
  style: compressed

encoding: utf-8
